# This file contains configuration overrides for places returned by the Google Places API.
# These allow for modifying name, tags, etc. and can be expanded as needed by adding modifiers
# in the Map::Pipeline::* module
tags:
  art:
    prompt: Visit art galleries
  beer:
    prompt: Grab a local beer
  cocktails:
    prompt: Enjoy a craft cocktail
  lunch:
    prompt: Find a lunch spot
  dinner:
    prompt: Sit down for a nice dinner
  nightlife:
    prompt: Take in the nightlife
  thrifting_and_anitiques:
    prompt: Thrift or browse antiques
  coffee:
    prompt: Sip some coffee/tea
  gifts_and_decor:
    prompt: Walk and shop, gifts and decor
  home_goods:
    prompt: Walk and shop, home goods
  tourism:
    prompt: See the local attractions

# Hash on google place ID for fastest lookup
places:
  ChIJKenXYKhS6IARFUFcI0rGlUs:
    name: "Latitudes Gallery"
    tags:
      - art
  ChIJ6QyTvHOt6YAR0oLhK5Yi4zs:
    tags:
      - art
  ChIJgUw9hPGs6YARxJfqQ3oZl7Q:
    tags:
      - art

  ChIJZw0Zpvqs6YARz4qVaynBwGs:
    name: "Betty Belts"
    tags:
      - art
  ChIJY30Ombmt6YARvdKggb6FdeI:
    tags:
      - art
  ChIJPduuJACt6YARvzVPFPe9C8M:
    tags:
      - art
  ChIJP3eCy9it6YARZD-hs5iSeFk:
    tags:
      - art

  ChIJ9_46V9ut6YARUys_TjOSN0o:
    name: "Finney's Crafthouse"

  ChIJZeCnPcqt6YARjVsfRjNQoKY:
    name: "House of Culture Ventura"

  ChIJFbA0s--s6YARH77sud21AA4:
    name: "Rip Curl"

  ChIJ2e03iDGt6YARQoAxvrb73hI:
    name: "Eclecteak"

  ChIJxdlFfbut6YARDluOou9TMcs:
    name: "Channel Islands Juice Co."

  ChIJD_Glnfqs6YAR8m4DP3zz744:
    name: "Maison De Michelle"

  ChIJJ25_pPGs6YARVxIpppRldzU:
    name: "Brooklyn Charm"

  ChIJsT-X4Wet6YARJ7GV-DmFNA4:
    name: "Amanzi Hotel"

  ChIJVZFrWO6s6YARr9JVYuVgUWY:
    name: "Crowne Plaza Ventura Beach"

  ChIJkwkaDO6s6YARRHH-6dR5kIU:
    name: "Motel 6"

bogus:
  ChIJq6rqUOWs6YARHcq4Vo4TTCU: true
  ChIJwXt0aDqt6YARawGwIgWT1lM: true
  ChIJI2GXQqyt6YARooHQeM4M9p0: true
  ChIJ_ztNZF6t6YARhei8iyUPO2M: true
  ChIJUWWFofGs6YARtB1qOA_cxjo: true
  ChIJba3geQCt6YARh7ieRFrvNvo: true
